### ISSUE TITLE
The bug is too much!

### ISSUE THREAD

**Issue by zhangxiaodi** [thodan/bop_toolkit#8]
Traceback (most recent call last):
  File "/home/znb/research/bop_toolkit/scripts/render_train_imgs.py", line 115, in <module>
    ren_rgb.set_light_ambient_weight(ambient_weight)
  File "/home/znb/research/bop_toolkit/bop_toolkit_lib/renderer_cpp.py", line 34, in set_light_ambient_weight
    self.renderer.set_light_ambient_weight(light_ambient_weight)
AttributeError: 'bop_renderer.Renderer' object has no attribute 'set_light_ambient_weight'

**Comment by zhangxiaodi** [comment]
i want to know that are you really test renderer_cpp.py?

**Comment by thodan** [comment]
Fixed.
