### ISSUE TITLE
installation issue in Python 3.10

### ISSUE THREAD

**Issue by monajalal** [thodan/bop_toolkit#92]
```
(zephyr) mona@ard-gpu-01:~/zephyr/external/bop_toolkit$ pip install -r requirements.txt -e .
Obtaining file:///home/mona/zephyr/external/bop_toolkit
  Preparing metadata (setup.py) ... done
Collecting git+https://github.com/MartinSmeyer/cocoapi.git@v1.0#subdirectory=PythonAPI (from -r requirements.txt (line 12))
  Cloning https://github.com/MartinSmeyer/cocoapi.git (to revision v1.0) to /tmp/pip-req-build-b8_nftpc
  Running command git clone --filter=blob:none --quiet https://github.com/MartinSmeyer/cocoapi.git /tmp/pip-req-build-b8_nftpc
  Running command git checkout -q b114069f17162f704f20de15bbb15838305e960e
  Resolved https://github.com/MartinSmeyer/cocoapi.git to commit b114069f17162f704f20de15bbb15838305e960e
  Preparing metadata (setup.py) ... done
Collecting scipy==1.5.1 (from -r requirements.txt (line 1))
  Using cached scipy-1.5.1.tar.gz (25.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [176 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting wheel
        Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting setuptools
        Using cached setuptools-67.8.0-py3-none-any.whl (1.1 MB)
      Collecting Cython>=0.29.18
        Downloading Cython-0.29.35-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 11.6 MB/s eta 0:00:00
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pybind11>=2.4.3
        Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [124 lines of output]
            Running from numpy source directory.
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['/home/mona/anaconda3/envs/zephyr/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            blis_info:
            customize UnixCCompiler
              libraries blis not found in ['/home/mona/anaconda3/envs/zephyr/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            openblas_info:
            customize UnixCCompiler
            customize UnixCCompiler
              libraries openblas not found in ['/home/mona/anaconda3/envs/zephyr/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries tatlas not found in ['/home/mona/anaconda3/envs/zephyr/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_3_10_blas_info:
            customize UnixCCompiler
              libraries satlas not found in ['/home/mona/anaconda3/envs/zephyr/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries ptf77blas,ptcblas,atlas not found in ['/home/mona/anaconda3/envs/zephyr/lib', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu/atlas', '/usr/lib/x86_64-linux-gnu']
              NOT AVAILABLE
      
            atlas_blas_info:
            customize UnixCCompiler
            get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
            customize Gnu95FCompiler
            Found executable /usr/bin/gfortran
            customize Gnu95FCompiler
            customize Gnu95FCompiler using config
            compiling '_configtest.c':
      
            /* This file is generated from numpy/distutils/system_info.py */
            void ATL_buildinfo(void);
            int main(void) {
              ATL_buildinfo();
              return 0;
            }
      
            C compiler: gcc -pthread -B /home/mona/anaconda3/envs/zephyr/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/mona/anaconda3/envs/zephyr/include -fPIC -O2 -isystem /home/mona/anaconda3/envs/zephyr/include -fPIC
      
            compile options: '-c'
            gcc: _configtest.c
            gcc -pthread -B /home/mona/anaconda3/envs/zephyr/compiler_compat _configtest.o -L/usr/lib/x86_64-linux-gnu -lf77blas -lcblas -latlas -o _configtest
            /home/mona/anaconda3/envs/zephyr/compiler_compat/ld: warning: libm.so.6, needed by /usr/lib/x86_64-linux-gnu/libatlas.so, not found (try using -rpath or -rpath-link)
            /home/mona/anaconda3/envs/zephyr/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/libatlas.so: undefined reference to `sqrtl@GLIBC_2.2.5'
            /home/mona/anaconda3/envs/zephyr/compiler_compat/ld: /usr/lib/x86_64-linux-gnu/libatlas.so: undefined reference to `sqrt@GLIBC_2.2.5'
            collect2: error: ld returned 1 exit status
            failure.
            removing: _configtest.c _configtest.o _configtest.o.d
            Status: 255
            Output: compiling '_configtest.c':
      
            /* This file is generated from numpy/distutils/system_info.py */
            void ATL_buildinfo(void);
            int main(void) {
              ATL_buildinfo();
              return 0;
            }
      
            C compiler: gcc -pthread -B /home/mona/anaconda3/envs/zephyr/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/mona/anaconda3/envs/zephyr/include -fPIC -O2 -isystem /home/mona/anaconda3/envs/zephyr/include -fPIC
      
            compile options: '-c'
            gcc: _configtest.c
            gcc -pthread -B /home/mona/anaconda3/envs/zephyr/compiler_compat _configtest.o -L/usr/lib/x86_64-linux-gnu -lf77blas -lcblas -latlas -o _configtest
      
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/setup.py", line 443, in <module>
                setup_package()
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/setup.py", line 435, in setup_package
                setup(**metadata)
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/core.py", line 137, in setup
                config = configuration()
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/setup.py", line 158, in configuration
                config.add_subpackage('numpy')
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/misc_util.py", line 1033, in add_subpackage
                config_list = self.get_subpackage(subpackage_name, subpackage_path,
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/misc_util.py", line 999, in get_subpackage
                config = self._get_configuration_from_setup_py(
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
                config = setup_module.configuration(*args)
              File "numpy/setup.py", line 10, in configuration
                config.add_subpackage('core')
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/misc_util.py", line 1033, in add_subpackage
                config_list = self.get_subpackage(subpackage_name, subpackage_path,
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/misc_util.py", line 999, in get_subpackage
                config = self._get_configuration_from_setup_py(
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
                config = setup_module.configuration(*args)
              File "numpy/core/setup.py", line 764, in configuration
                blas_info = get_info('blas_opt', 0)
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 444, in get_info
                return cl().get_info(notfound_action)
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 690, in get_info
                self.calc_info()
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 1810, in calc_info
                if getattr(self, '_calc_info_{}'.format(blas))():
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 1756, in _calc_info_atlas
                info = get_info('atlas_blas')
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 444, in get_info
                return cl().get_info(notfound_action)
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 690, in get_info
                self.calc_info()
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 1294, in calc_info
                atlas_version, atlas_extra_info = get_atlas_version(**atlas)
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 1589, in get_atlas_version
                'ATLAS_INFO', _c_string_literal(atlas_version))
              File "/tmp/pip-install-8s47yas_/numpy_9e217113a6c34c6cb058c2221ebf7e0a/numpy/distutils/system_info.py", line 177, in _c_string_literal
                s = s.replace('\\', r'\\')
            AttributeError: 'NoneType' object has no attribute 'replace'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by monajalal** [comment]
```
2132  cat requirements.txt 
 2133  pip install --no-cache-dir scipy
 2134  pip install --no-cache-dir kiwisolver
 2135  pip install --no-cache-dir matplotlib
 2136  pip install --no-cache-dir imageio
 2137  pip install --no-cache-dir pypng
 2138  pip install --no-cache-dir Cython
 2139  pip install --no-cache-dir PyOpenGL
 2140  pip install --no-cache-dir triangle
 2141  pip install --no-cache-dir glumpy
 2142  pip install --no-cache-dir opencv-python
 2143  pip install --no-cache-dir Pillow
 2146  pip install git+https://github.com/MartinSmeyer/cocoapi.git@v1.0#subdirectory=PythonAPI 
 2147  pip install vispy
 2148  python setup.py install
```
